### ISSUE TITLE
Applying weights to fields using Pyterrier for BM25F model

### ISSUE THREAD

**Issue by soydanielle** [cmacdonald/pyterrier_bert#7]
Hi, I have been trying to find somewhere in the documentation on how to apply weights to fields as I'm using BM25F for a dataset. Would you be able to let me know if there's a function on Pyterrier in which can be used.

**Comment by cmacdonald** [comment]
Hi, Can we have this discussion on the main PyTerrier repository - https://github.com/terrier-org/pyterrier/issues

**Comment by soydanielle** [comment]
Sure thanks
